# Generated by Django 5.2.15 on 2026-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the project title.', max_length=160)),
                ('project_type', models.CharField(choices=[('machine_learning', 'Machine Learning'), ('ai_chatbot', 'AI Chatbot'), ('ai_agent', 'AI Agent'), ('cybersecurity', 'Cybersecurity'), ('operating_systems', 'Operating Systems'), ('web_development', 'Web Development'), ('other', 'Other')], default='other', max_length=30)),
                ('short_description', models.CharField(help_text='A short description displayed prominently on the card.', max_length=280)),
                ('description', models.TextField(help_text='Explain the project, its purpose, and your contribution.')),
                ('technologies', models.CharField(help_text='Separate technologies using commas.', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Optional project screenshot or image.', null=True, upload_to='projects/')),
                ('repository_status', models.CharField(choices=[('public', 'Public Repository'), ('private', 'Private Repository'), ('no_repository', 'No Public Repository')], default='no_repository', max_length=20)),
                ('github_url', models.URLField(blank=True, help_text='Required only when the repository is public.')),
                ('live_url', models.URLField(blank=True, help_text='Optional deployed project or demonstration link.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark important projects as featured.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active projects appear on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
