# Generated by Django 5.2.15 on 2026-06-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text='For example: BS Computer Science or Intermediate.', max_length=150)),
                ('institution', models.CharField(help_text='Enter the school, college, or university name.', max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text='For example: Computer Science.', max_length=150)),
                ('location', models.CharField(blank=True, help_text='For example: Lahore, Pakistan.', max_length=120)),
                ('start_year', models.PositiveSmallIntegerField(help_text='Enter the year in which this qualification started.')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if this qualification is currently in progress.', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Select this if you are currently studying here.')),
                ('grade', models.CharField(blank=True, help_text='Optional: CGPA, percentage, grade, or division.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Add relevant academic details or achievements.')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active records are displayed on the portfolio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'ordering': ['display_order', '-start_year', '-id'],
            },
        ),
    ]
