```python
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------
# SECURITY AND ENVIRONMENT SETTINGS
# ------------------------------------------------------------------

# Render automatically creates the RENDER environment variable.
IS_RENDER = bool(os.environ.get("RENDER"))

# Local development uses DEBUG=True by default.
# Render uses DEBUG=False by default.
DEBUG = (
    os.environ.get(
        "DJANGO_DEBUG",
        "False" if IS_RENDER else "True",
    ).lower()
    == "true"
)

# During local development, Django can use this temporary fallback key.
# During production, DJANGO_SECRET_KEY must be configured on Render.
if DEBUG:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-local-development-only",
    )
else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

    if not SECRET_KEY:
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be configured in the "
            "production environment."
        )


# Hosts allowed during local development.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Render automatically provides its deployed hostname.
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Additional hosts can be added through an environment variable.
# Example:
# DJANGO_ALLOWED_HOSTS=12345678.netlify.app,my-domain.com
EXTRA_ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "",
)

ALLOWED_HOSTS.extend(
    host.strip()
    for host in EXTRA_ALLOWED_HOSTS.split(",")
    if host.strip()
)

# Remove duplicate host entries.
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Trusted HTTPS origins for Django forms and Admin.
CSRF_TRUSTED_ORIGINS = []

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )


# Additional trusted origins can be supplied during deployment.
# Example:
# DJANGO_CSRF_TRUSTED_ORIGINS=https://12345678.netlify.app
EXTRA_CSRF_ORIGINS = os.environ.get(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
)

CSRF_TRUSTED_ORIGINS.extend(
    origin.strip()
    for origin in EXTRA_CSRF_ORIGINS.split(",")
    if origin.strip()
)

CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(CSRF_TRUSTED_ORIGINS)
)


# Security settings used when the project is deployed.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ------------------------------------------------------------------
# APPLICATION DEFINITION
# ------------------------------------------------------------------

INSTALLED_APPS = [
    # Django built-in applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Portfolio applications
    "core.apps.CoreConfig",
    "bio.apps.BioConfig",
    "education.apps.EducationConfig",
    "skills.apps.SkillsConfig",
    "experience.apps.ExperienceConfig",
    "projects.apps.ProjectsConfig",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth.context_processors."
                    "auth"
                ),
                (
                    "django.contrib.messages.context_processors."
                    "messages"
                ),
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# ------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ------------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ------------------------------------------------------------------
# STATIC FILES
# CSS, JavaScript, icons, and website design assets
# ------------------------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Deployment services collect static files into this folder.
STATIC_ROOT = BASE_DIR / "staticfiles"


# ------------------------------------------------------------------
# MEDIA FILES
# Profile pictures and project images
# ------------------------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# ------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
```
