```python
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


# ---------------------------------------------------------------
# BASE DIRECTORY
# ---------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------
# SECURITY AND ENVIRONMENT SETTINGS
# ---------------------------------------------------------------

# Render automatically creates this environment variable.
IS_RENDER = bool(os.environ.get("RENDER"))


# DEBUG is True on the local computer and False on Render.
DEBUG = (
    os.environ.get(
        "DJANGO_DEBUG",
        "False" if IS_RENDER else "True",
    ).lower()
    == "true"
)


# Local development uses a temporary fallback key.
# Production requires DJANGO_SECRET_KEY in Render.
if DEBUG:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-local-development-only",
    )
else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

    if not SECRET_KEY:
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be configured "
            "in the production environment."
        )


# Hosts permitted during local development.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Render provides its deployed hostname automatically.
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Additional hosts can be supplied through an environment variable.
#
# Example:
# DJANGO_ALLOWED_HOSTS=12345678.netlify.app
EXTRA_ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "",
)

ALLOWED_HOSTS.extend(
    host.strip()
    for host in EXTRA_ALLOWED_HOSTS.split(",")
    if host.strip()
)

# Remove duplicate values.
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# ---------------------------------------------------------------
# CSRF TRUSTED ORIGINS
# ---------------------------------------------------------------

CSRF_TRUSTED_ORIGINS = []


# Trust the Render HTTPS address.
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )


# Additional origins can be supplied during deployment.
#
# Example:
# DJANGO_CSRF_TRUSTED_ORIGINS=https://12345678.netlify.app
EXTRA_CSRF_ORIGINS = os.environ.get(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
)

CSRF_TRUSTED_ORIGINS.extend(
    origin.strip()
    for origin in EXTRA_CSRF_ORIGINS.split(",")
    if origin.strip()
)

CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(CSRF_TRUSTED_ORIGINS)
)


# Production security configuration.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ---------------------------------------------------------------
# APPLICATION DEFINITION
# ---------------------------------------------------------------

INSTALLED_APPS = [
    # Django built-in applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Portfolio applications
    "core.apps.CoreConfig",
    "bio.apps.BioConfig",
    "education.apps.EducationConfig",
    "skills.apps.SkillsConfig",
    "experience.apps.ExperienceConfig",
    "projects.apps.ProjectsConfig",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise serves CSS, JavaScript, and collected static files.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django.DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------
# DATABASE
# ---------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ---------------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ---------------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------
# STATIC FILES
# CSS, JavaScript, icons, and design assets
# ---------------------------------------------------------------

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# WhiteNoise storage compresses static files and generates
# versioned filenames for browser caching.
STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# ---------------------------------------------------------------
# MEDIA FILES
# Profile pictures and project images
# ---------------------------------------------------------------

MEDIA_ROOT = BASE_DIR / "media"


# Locally, Django serves uploaded files from /media/.
#
# On Render, the media folder already stored in the repository
# is collected with the static files so the existing profile
# picture remains available.
if IS_RENDER:
    MEDIA_URL = "/static/media/"

    STATICFILES_DIRS.append(
        (
            "media",
            MEDIA_ROOT,
        )
    )
else:
    MEDIA_URL = "/media/"


# ---------------------------------------------------------------
# DEFAULT PRIMARY KEY
# ---------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
```
