# Generated by Django 5.2.15 on 2026-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your complete professional name.', max_length=100)),
                ('job_title', models.CharField(help_text='For example: Cybersecurity Student or Python Developer.', max_length=150)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a professional profile picture.', null=True, upload_to='profiles/')),
                ('professional_description', models.TextField(help_text='Write a short professional introduction.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active Bio records can appear on the portfolio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bio',
                'ordering': ['-updated_at'],
            },
        ),
    ]
