# Generated by Django 5.2.15 on 2026-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For example: Cybersecurity Researcher or AI Techathon Participant.', max_length=150)),
                ('organization', models.CharField(help_text='Company, university, platform, or organization name.', max_length=180)),
                ('experience_type', models.CharField(choices=[('professional', 'Professional'), ('academic', 'Academic'), ('internship', 'Internship'), ('competition', 'Competition'), ('volunteer', 'Volunteer')], default='academic', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check this when the experience is still continuing.')),
                ('description', models.TextField(help_text='Explain your responsibilities, work, and achievements.')),
                ('technologies', models.CharField(blank=True, help_text='Separate technologies using commas.', max_length=250)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['display_order', '-start_year', '-id'],
            },
        ),
    ]
