# Generated by Django 5.2.15 on 2026-06-21 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example: Python, Nmap, Django, or Communication.', max_length=100)),
                ('category', models.CharField(choices=[('cybersecurity', 'Cybersecurity'), ('programming', 'Programming'), ('web_development', 'Web Development'), ('database', 'Database'), ('networking', 'Networking'), ('tools', 'Tools and Technologies'), ('professional', 'Professional Skills')], default='tools', max_length=30)),
                ('proficiency', models.PositiveSmallIntegerField(default=70, help_text='Enter a proficiency value from 1 to 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(blank=True, help_text='Optional short explanation of your experience.', max_length=250)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active skills appear on the portfolio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_skill_per_category')],
            },
        ),
    ]
